"""Exports the open .blend to .glb with the project's glTF settings (settings.py).

Run inside Blender 4.5:
    blender --background <file.blend> --python export_glb.py -- --out <file.glb>

Events: pose markers on the actions (Action Editor, "Show Pose Markers") are the source of truth.
If any action has markers, <file>.events.toml is written next to the .glb (frames relative to
the action start); otherwise an existing events file is left alone.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import bpy  # type: ignore[import-not-found]

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from gothar_chargen.blender.settings import GLTF_EXPORT_SETTINGS  # noqa: E402
from gothar_chargen.events import Event, events_path_for, format_events  # noqa: E402
from gothar_chargen.naming import is_clip_name  # noqa: E402


def _marker_events() -> dict[str, list[Event]]:
    clips: dict[str, list[Event]] = {}
    for action in bpy.data.actions:
        if not is_clip_name(action.name) or not action.pose_markers:
            continue
        start = int(round(action.frame_range[0]))
        clips[action.name] = [Event(m.frame - start, m.name) for m in action.pose_markers]
    return clips


def _parse_args() -> argparse.Namespace:
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(prog="export_glb")
    parser.add_argument("--out", type=Path, required=True, help="output .glb")
    return parser.parse_args(argv)


def main() -> None:
    args = _parse_args()
    if bpy.context.object is not None and bpy.context.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    result = bpy.ops.export_scene.gltf(filepath=str(args.out.resolve()), **GLTF_EXPORT_SETTINGS)
    if "FINISHED" not in result:
        print(f"[chargen] export failed: {result}", file=sys.stderr)
        sys.exit(1)
    print(f"[chargen] wrote {args.out}")
    events = _marker_events()
    if events:
        path = events_path_for(args.out)
        header = "# Generated by gothar-chargen export from pose markers (edit the markers).\n"
        text = header + format_events(bpy.context.scene.render.fps, events)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"[chargen] wrote {path}")


if __name__ == "__main__":
    main()
